apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: efk-logs
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    role: client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        role: client
    spec:
      serviceAccountName: es-client
      containers:
      - name: es-client
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: kayrus/docker-elasticsearch-kubernetes:2.4.4
        args:
        - /run.sh
        - -Des.path.conf=/etc/elasticsearch
        readinessProbe:
          httpGet:
            path: /
            port: 9200
            scheme: HTTP
          timeoutSeconds: 1
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 360
          timeoutSeconds: 2
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-config
          mountPath: /etc/elasticsearch
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NODE_MASTER
          value: 'false'
        - name: NODE_DATA
          value: 'false'
        - name: HTTP_ENABLE
          value: 'true'
        - name: ES_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-heap
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
      volumes:
      - name: es-config
        configMap:
          name: es-config