apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: efk-logs
  labels:
    k8s-app: elasticsearch-logging
    master: 'true'
spec:
  selector:
    k8s-app: elasticsearch-logging
    master: 'true'
  ports:
  - name: transport
    port: 9300
    protocol: TCP
