apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-data
  namespace: efk-logs
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    role: data
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        role: data
    spec:
      serviceAccountName: es-data
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: kayrus/docker-elasticsearch-kubernetes:2.4.4
        args:
        - /run.sh
        - -Des.path.conf=/etc/elasticsearch
        readinessProbe:
          tcpSocket:
            port: 9300
          timeoutSeconds: 1
          successThreshold: 3
        imagePullPolicy: Always
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        # Random hostPort to prevent multiple ES data instances on one node
        - name: dummy
          containerPort: 28651
          protocol: TCP
          hostPort: 28651
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        - name: es-config
          mountPath: /etc/elasticsearch
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NUMBER_OF_REPLICAS
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-number-of-replicas
        - name: NODE_MASTER
          value: 'false'
        - name: NODE_DATA
          value: 'true'
        - name: HTTP_ENABLE
          value: 'false'
        - name: ES_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-data-heap
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
        - name: ES_PERSISTENT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-persistent-storage
      terminationGracePeriodSeconds: 31557600
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
      - name: es-config
        configMap:
          name: es-config