apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: efk-logs
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/name: "Elasticsearch"
    component: elasticsearch
    role: client
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
    nodePort: 30019
  selector:
    k8s-app: elasticsearch-logging