apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: efk-logs

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: fluentd
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: efk-logs
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io