apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-es-v1.22
  namespace: efk-logs
  labels:
    k8s-app: fluentd-es
    version: v1.22
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        version: v1.22
    spec:
      serviceAccountName: fluentd
      # hostNetwork: true
      containers:
      - name: fluentd-es
        image: tianctrl/k8s-fluentd-image
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/sbin/td-agent $FLUENTD_ARGS'
        env:
        - name: FLUENTD_AGRS
          value: -q
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 5140
          name: log
          protocol: UDP
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
