apiVersion: v1
kind: Service
metadata:
  name: fluentd-logging
  namespace: efk-logs
  labels:
    k8s-app: fluentd-es
    kubernetes.io/name: "Fluentd"
spec:
  type: NodePort
  ports:
  - port: 5140
    protocol: UDP
    targetPort: 5140
    nodePort: 30140
  selector:
    k8s-app: fluentd-es