apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-{{ template "fullname" . }}
  labels:
    k8s-app: elasticsearch-logging-{{ template "fullname" . }}
    kubernetes.io/name: "Elasticsearch"
    component: elasticsearch
    role: client
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
  selector:
    k8s-app: elasticsearch-logging-{{ template "fullname" . }}