apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-es-{{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: fluentd-es-{{ template "fullname" . }}
    version: v1.22
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-es-{{ template "fullname" . }}
        version: v1.22
    spec:
      serviceAccountName: fluentd-{{ template "fullname" . }}
      containers:
      - name: fluentd-es-{{ template "fullname" . }}
        image: {{ .Values.fluentd.image }}
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/sbin/td-agent $FLUENTD_ARGS'
        env:
        - name: FLUENTD_AGRS
          value: -q
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
